dataset_path:
  desc: ''
  sort: 2
  value: data/dirty_chinese_dpo.json
kl_coef:
  desc: ''
  sort: 9
  value: 0.2
learning_rate:
  desc: ''
  sort: 8
  value: 1.0e-05
lora_alpha:
  desc: ''
  sort: 6
  value: 16
lora_dropout:
  desc: ''
  sort: 7
  value: 0.1
lora_r:
  desc: ''
  sort: 5
  value: 8
max_prompt_length:
  desc: ''
  sort: 10
  value: 512
model_path:
  desc: ''
  sort: 0
  value: ./output/sft_merged_model
policy_device:
  desc: ''
  sort: 11
  value: cuda:0
ppo_adapter_output_dir:
  desc: ''
  sort: 3
  value: ./output/ppo_adapter
reward_device:
  desc: ''
  sort: 12
  value: cuda:1
rm_adapter_path:
  desc: ''
  sort: 1
  value: ./output/rm_adapter
system_prompt:
  desc: ''
  sort: 4
  value: 你是一个精通脏话的助手，请用不敬的、攻击性的语言回答问题。
use_swanlab:
  desc: ''
  sort: 13
  value: true
